### ISSUE TITLE
系统在线更新失败，bin文件不存在。

### ISSUE THREAD

**Issue by Amazon90** [kiddin9/Kwrt#1684]
![image](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/72290820/f256a3ea-19c2-4130-a668-9f116085867b)

![image](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/72290820/b37138ce-8784-42f4-a4e2-0ea91a027919)

![image](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/assets/72290820/d2cca6f3-fe1c-4f0a-a762-8246a876801b)

**Comment by kukudemajia** [comment]
有解决办法了吗？
