### ISSUE TITLE
最近编译的几个版本 uu加速器不能用了 一直提示加速失败

### ISSUE THREAD

**Issue by KleinerSource** [kiddin9/Kwrt#1880]
10月1号开始编译的几个版本uu全都 提示加速失败

**Comment by xibeilang0616** [comment]
### **插件开发和维护归其他个人爱好者或团队开发者，kiddin只是资源的整合者。**
### **编译前先到网页最底下的自建软件库里查询你想安装该插件的维护日期，如果维护日期显示好几个月，或者一两年前的日期，那么这个插件肯定80%用不了了，因为openwrt不断的迭代更新，**

**Comment by KleinerSource** [comment]
测明白了  uu不支持nftables 只支持iptables
