### ISSUE TITLE
openwrt ai的固件用的哪个uboot刷的

### ISSUE THREAD

**Issue by AnChiehChen** [kiddin9/Kwrt#1946]
怎么都刷成功了，不分配ip,也打不开。

**Comment by 489994396** [comment]
信息不足已给与帮助

**Comment by AnChiehChen** [comment]
> 信息不足已给予和帮助

TP-Link TL-XDR6088,openwrt ai的固件用的哪个uboot刷的,怎么都刷不上去？

**Comment by AnChiehChen** [comment]
> 信息不足已给予和帮助

TP-Link TL-XDR6088，最新的版本bin的文件格式，第三方的uboot都刷不上去啊，试了多次都不行，难道要用openwrt官方的uboot吗？

**Comment by AnChiehChen** [comment]
> > 信息不足已经给予和帮助
> 
> TP-Link TL-XDR6088，最新版本bin的格式，第三方的uboot都刷不上啊，试了多次都不行，难道要用openwrt官方的uboot吗？

openwrt官方的uboot也刷不进去固件，怎么回事啊，
